export interface IOwnerInfo{
    createdBy?:string,
    createdDate?: Date,
    database?: string,
    description?: string,
    email?: string,
    englishName?: string,
    faceboolURL?: string,
    id?: number,
    inURL?: string,
    instagramURL?: string,
    name?: string,
    pathImage?: string,
    phone?: string,
    phone1?: string,
    recordCount?: number,
    telegramURL?: string,
    updatedBy?: string,
    updatedDate?: Date,
    workingInfo?: string,
    youtubeURL?: string,
    descriptionEnglish?: string,
    subDescription?: string,
    subDescriptionEnglish?: string,
}